### ISSUE TITLE
Daisy chained L9963E not working, here's a fix

### ISSUE THREAD

**Issue by Zuikkis** [squadracorsepolito/L9963E_lib#1]
Hi!

Thanks for this excellent library. ST themself couldn't  provide any examples how to handle their chip with their CPU (stm32), but with your library I was getting results in a few hours. :)

However I could only talk to the first device in the chain. Digging this further, I think I found a bug in L9963E.c:

https://github.com/squadracorsepolito/L9963E_lib/blob/e99b08e613fe00cfdcbe8339c2db28d3999bfb66/src/L9963E.c#L63-L74

I browsed through the data sheet and noticed this about the wakeup procedure:

"However, while in Init state, only the chip_ID, **isotx_en_h** and iso_freq_sel fields are writable. It is not possible to write/read other registers."

So.. isotx_en_h enables the ISOH port. That's why my daisy chained chips don't work. The wake up loop enables chip #1 but doesn't enable the ISOH port, so next chip can't be woken up. 

Add this line to above code, and it starts working:
            write_reg.DEV_GEN_CFG.isotx_en_h     = 0b1;

I do still have another problem that iso_freq_sel=0b11 is not working, but then again I think the lower speed is enough for me.

**Comment by federico-carbone** [comment]
Thank you! I really appreciate your words.
Just fixed it.

**Comment by ichbinbork** [comment]
Hey @Zuikkis . Did you make other changes also in source code. According to datasheet "isotx_en_h" must be 0  for last slave device in the Centralized BMS architecture. Therefore I have added these lines.

`
          write_reg.DEV_GEN_CFG.isotx_en_h   = 0b1;
           if (x == handle->slave_n ){
              write_reg.DEV_GEN_CFG.isotx_en_h   = 0b0;
          }
`
So far my code compiled but I couldn't communicate with the slave IC. 


So I have two question for you: 

Which architecture do you use to communicate slave IC's?

Are you using transceiver or not ?

**Comment by Zuikkis** [comment]
I replied in your other issue already. The current code is correct. Your code above should work too, but isotx_en_h is set to 0 by default code also.

I initially had problem that  iso_freq_sel=0b11 (higher SPI speed) was not working, but it's because my test code only polled at 1sec intervals and I had comm timeout set to 256ms.. After the timeout all chips reset back to slow speed and need to be reconfigured again. There is no provision in the code to detect this situation. But this shouldn't happen normally when you are constantly polling, and also timeout can be increased to 2048ms for example.

**Comment by federico-carbone** [comment]
Yes i faced the same problem some time ago. @ichbinbork actually spotted an issue in the wakeup function which might solve this issue, i was not able to test it (here the [commit](https://github.com/squadracorsepolito/L9963E_lib/commit/e99b08e613fe00cfdcbe8339c2db28d3999bfb66)).

Did you tried it after this change? The datasheet is not very clear
![image](https://github.com/user-attachments/assets/be19003c-a060-48ea-9cf1-182a0d93ea8f)

I found that in order for a pulse to be longer than T_{DET_MIN_WU}, the communication must be set to isofreq_low. @Zuikkis did you already tried it after this last change?

**Comment by Zuikkis** [comment]
@federico-carbone yes I am using that version, it works. But the issue is, if chips enter sleep, L9963E_DRV_wakeup() must be called manually for them to work again. 

But it's reasonably easy to do in your main loop. If you start getting timeouts, just try wakeup..

But, if slower speed is enough, it's easy because any normal comms will also wake up the chips.

**Comment by federico-carbone** [comment]
ok, thanks for the feedback, i was in contact with the people in ST developing their driver and apparently they were not aware of this issue. I think it interfer with cyclic wakeup so i will definitely try to solve this problem, sooner or later.

**Comment by ichbinbork** [comment]
I'm using also [commit](https://github.com/squadracorsepolito/L9963E_lib/commit/e99b08e613fe00cfdcbe8339c2db28d3999bfb66) and it works fine with single IC.  However, I couldn't see the second slave device voltage values. addressing procedure work fine for both slave device with these parameters.

```
L9963E_init(&h9l, interface, 2);
L9963E_addressing_procedure(&h9l, 0b00, 0, 0b00, 1);     
```

But, my program stucks while polling second slave
```
  do {
    L9963E_poll_conversion(&h9l, device, &c_done);
  } while (!c_done);
```
