### ISSUE TITLE
Daisy chain Centralized BMS potential bug

### ISSUE THREAD

**Issue by ichbinbork** [squadracorsepolito/L9963E_lib#2]
Hey,

I want to use daisy chain structure with ISOSPI with multiple L9963E. According to datasheet last L9963E slave "isotx_en_h" parameter must be 0 to achive it. However, at current code the given parameter always set 1 with  `write_reg.DEV_GEN_CFG.isotx_en_h     = 0b1;.` 

There is a section that the parameter set 0 but its only for dual ring access in my scenario I won't use it . 

```
    if (!handle->is_dual_ring) {
        write_reg.DEV_GEN_CFG.isotx_en_h = 0;
    }
```

I made changes but unfortunately I couldn't test it yet. When I test it I will create pr.

Sincerely,

![image](https://github.com/user-attachments/assets/f6fc8fe8-5451-4b70-a25a-7783ba573588)

**Comment by Zuikkis** [comment]
> Hey,
> 
> I want to use daisy chain structure with ISOSPI with multiple L9963E. According to datasheet last L9963E slave "isotx_en_h" parameter must be 0 to achive it. However, at current code the given parameter always set 1 with `write_reg.DEV_GEN_CFG.isotx_en_h = 0b1;.`
> 
> There is a section that the parameter set 0 but its only for dual ring access in my scenario I won't use it .
> 
> ```
>     if (!handle->is_dual_ring) {
>         write_reg.DEV_GEN_CFG.isotx_en_h = 0;
>     }
> ```

Hmm, you have misundestood that line. It says "if NOT dual ring, disable isotx_en_h". So it is working as intended.

I have exactly this topology in my system and it is working.

**Comment by federico-carbone** [comment]
Hello @ichbinbork, if you look closely, that line of code executes only when is NOT a dual ring configuration, which is your use case.
Thanks.
